notifications:
  slack: tutorbookapp:TO4yyYMKazQGLZ0isrytycru
branches:
  only:
  - master
  - gunn
  - paly
  - jls
language: node_js
node_js:
- '10.10'
cache:
  directories:
  - "/home/travis/.cache/firebase/emulators"
jobs:
  include:
  - stage: test
    before_install:
    - openssl aes-256-cbc -K $encrypted_643ae61e7902_key -iv
      $encrypted_643ae61e7902_iv -in firebase/functions/.runtimeconfig.json.enc
      -out firebase/functions/.runtimeconfig.json -d
    install:
    - npm install -g firebase-tools
    - cd firebase/
    - npm i
    - cd functions/
    - npm i
    before_script:
    - firebase emulators:start --only firestore,functions --project
      tutorbook-779d8 &>/dev/null &
    - sleep 5
    - cd ../
    script:
    - npm test
  - stage: deploy
    script:
    - firebase deploy --project tutorbook-779d8 --except functions --token
      "$FIREBASE_TOKEN" --message "$TRAVIS_COMMIT_MESSAGE"
